id: AA2E5DA95
title: Prayer of Truthful Words to Pacify the Fear of War
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.515701
  last_modified_at: 2022-03-01 02:51:20.515704
