id: AA2E5DA95
title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
  for Mind Training'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.532634
  last_modified_at: 2022-03-01 02:51:20.532637
