id: AA2E5DA95
title: Clouds of Offerings to Delight the Victorious Ones – An Aspiration Prayer for
  the Spread of the Teachings of the Lord of Siddhas, Dzogchen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.482042
  last_modified_at: 2022-03-01 02:51:20.482045
