id: AA2E5DA95
title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.397520
  last_modified_at: 2022-03-01 02:51:20.397522
