id: AA2E5DA95
title: 'The Fulfilment of All Aims and Wishes: An Aspiration to Request the Safeguarding
  of Happiness in Tibet'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.537550
  last_modified_at: 2022-03-01 02:51:20.537553
