id: AA2E5DA95
title: Aspiration Written in Sadness During the Water Snake Year
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.417783
  last_modified_at: 2022-03-01 02:51:20.417786
