id: AA2E5DA95
title: Prayer of Aspiration for the Buddhist Teachings to Flourish in Taiwan
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.511412
  last_modified_at: 2022-03-01 02:51:20.511415
