id: AA2E5DA95
title: A Prayer of Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.400809
  last_modified_at: 2022-03-01 02:51:20.400812
