id: AA2E5DA95
title: Aspiration for the Stages of the Path
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.430441
  last_modified_at: 2022-03-01 02:51:20.430444
