id: AA2E5DA95
title: Aspirations in Accordance with the Dharma
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.474868
  last_modified_at: 2022-03-01 02:51:20.474871
