id: AA2E5DA95
title: 'Words of Truth: An Aspiration for the Spread of the Noble Gendenpa Tradition'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.615672
  last_modified_at: 2022-03-01 02:51:20.615674
