id: AA2E5DA95
title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
  of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.606985
  last_modified_at: 2022-03-01 02:51:20.606988
