id: AA2E5DA95
title: 'The Song of Devotion: Verses of Aspiration for the Fulfilment of the Enlightened
  Vision of Khenchen Jigme Phuntsok, the Reincarnation of Terton Lerab Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.593525
  last_modified_at: 2022-03-01 02:51:20.593527
