id: AA2E5DA95
title: 'The Sun of Samantabhadra’s Realm: The Quintessence of Oceanic Prayers of Aspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.597665
  last_modified_at: 2022-03-01 02:51:20.597668
