id: AA2E5DA95
title: A Brief Method for Reciting Samantabhadra's Prayer of Good Actions
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.390596
  last_modified_at: 2022-03-01 02:51:20.390603
