id: AA2E5DA95
title: Yeshe Tsogyal's Prayer
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.626561
  last_modified_at: 2022-03-01 02:51:20.626564
