id: AA2E5DA95
title: Aspiration Prayer
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.416738
  last_modified_at: 2022-03-01 02:51:20.416741
