id: AA2E5DA95
title: Aspiration for the Four Activities
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.424769
  last_modified_at: 2022-03-01 02:51:20.424772
