id: AA2E5DA95
title: Aspiration for the Spread of the Teachings of the Eight Chariots of the Practice
  Lineage
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.427914
  last_modified_at: 2022-03-01 02:51:20.427917
