id: AA2E5DA95
title: 'Wisdom''s Melody: An Aspiration to Realize Madhyamaka, Mahāmudrā, and Mahā
  Ati'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.613774
  last_modified_at: 2022-03-01 02:51:20.613777
