id: AA2E5DA95
title: Prayer of the View, Meditation and Conduct
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.517034
  last_modified_at: 2022-03-01 02:51:20.517037
