id: AA2E5DA95
title: Aspiration for Future Lives
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.422740
  last_modified_at: 2022-03-01 02:51:20.422743
