id: AA2E5DA95
title: 'Fostering Recollection to Dispel the Torment of Deluded Perception: An Aspiration
  for the Bardos'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.488620
  last_modified_at: 2022-03-01 02:51:20.488623
