id: AA2E5DA95
title: Prayer for the Future of the Dharma
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.506108
  last_modified_at: 2022-03-01 02:51:20.506110
