id: AA2E5DA95
title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
  Mountain of Glory
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.521523
  last_modified_at: 2022-03-01 02:51:20.521526
