id: AA2E5DA95
title: An Aspiration to Travel to the Hidden Land of Pemokö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.408298
  last_modified_at: 2022-03-01 02:51:20.408300
