id: AA2E5DA95
title: 'Declaration of the Power of Truth: A Prayer to Overcome Invading Forces'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.484820
  last_modified_at: 2022-03-01 02:51:20.484822
