id: AA2E5DA95
title: Aspiration for the Spread of the Guhyagarbha Teachings
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.426164
  last_modified_at: 2022-03-01 02:51:20.426167
