id: AA2E5DA95
title: The Prayer of the Words of Truth
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.572620
  last_modified_at: 2022-03-01 02:51:20.572622
