id: AA2E5DA95
title: Prayer of Aspiration Incorporating the Eight Thoughts of Great Beings Who Follow
  the Way of the Mahāyāna
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.508147
  last_modified_at: 2022-03-01 02:51:20.508150
