id: AA2E5DA95
title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
  Mountain of Glory'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.392546
  last_modified_at: 2022-03-01 02:51:20.392550
