id: AA2E5DA95
title: The Last Testament of Katok Dampa Deshek
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.556429
  last_modified_at: 2022-03-01 02:51:20.556432
