id: AA2E5DA95
title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly Secret,
  Enlightened Heart-Essence of the Ḍākinī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.602260
  last_modified_at: 2022-03-01 02:51:20.602262
