id: AA2E5DA95
title: 'Blazing Splendour of Good Fortune: A Prayer for the Spread of the Teachings
  of the Katok Tradition'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.476636
  last_modified_at: 2022-03-01 02:51:20.476639
