id: AA2E5DA95
title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.466439
  last_modified_at: 2022-03-01 02:51:20.466447
