id: AA2E5DA95
title: 'Entering the City of Omniscience: An Aspiration Prayer for Actualizing Words
  of Truth'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.486441
  last_modified_at: 2022-03-01 02:51:20.486444
