id: AA2E5DA95
title: An Aspirational Prayer to Behold the Beautiful Face of Khecharī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.411088
  last_modified_at: 2022-03-01 02:51:20.411091
