id: AA2E5DA95
title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of the Vast
  Expanse
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.569501
  last_modified_at: 2022-03-01 02:51:20.569504
