id: AA2E5DA95
title: Aspiration of the Mahāmudrā of Definitive Meaning
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.434776
  last_modified_at: 2022-03-01 02:51:20.434779
