id: AA2E5DA95
title: The Secret Vajra Knot
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.587566
  last_modified_at: 2022-03-01 02:51:20.587569
