id: AA2E5DA95
title: 'The Magical Lasso: A Prayer of Aspiration to Accomplish Khecara'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.560734
  last_modified_at: 2022-03-01 02:51:20.560737
