id: AA2E5DA95
title: Threefold Aspiration for Rebirth in Zangdok Palri
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.609043
  last_modified_at: 2022-03-01 02:51:20.609045
