id: AA2E5DA95
title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of Glory'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.584248
  last_modified_at: 2022-03-01 02:51:20.584251
