id: AA2E5DA95
title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.590929
  last_modified_at: 2022-03-01 02:51:20.590933
