id: AA2E5DA95
title: The Thirty Aspirations
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.600085
  last_modified_at: 2022-03-01 02:51:20.600088
