id: AA2E5DA95
title: Aspiration Prayer from Tārā Sādhana
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.414299
  last_modified_at: 2022-03-01 02:51:20.414302
