id: AA2E5DA95
title: Middle Way Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.494297
  last_modified_at: 2022-03-01 02:51:20.494300
