id: AA2E5DA95
title: 'The Jewelled Rosary: An Aspiration Toward Longed-for Aims'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.547714
  last_modified_at: 2022-03-01 02:51:20.547716
