id: AA2E5DA95
title: Prayer for the Flourishing of the Dzogchen Teachings of Sogyal Rinpoche, the
  incarnation of Lerab Lingpa
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.500855
  last_modified_at: 2022-03-01 02:51:20.500858
