id: AA2E5DA95
title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection that
  Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:51:20.565257
  last_modified_at: 2022-03-01 02:51:20.565260
